# Generated by Django 4.1.7 on 2023-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desg',
            field=models.TextField(default=('c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\python38.zip',)),
            preserve_default=False,
        ),
    ]
