# Generated by Django 4.1.7 on 2023-03-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_movie_desg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desg',
            new_name='desc',
        ),
    ]
